### ISSUE TITLE
Aplicacion de tareas

### ISSUE THREAD

**Issue by elnegrocok** [PeumaHue/ToDo#1]
Hola !! Esta es la aplicacion (https://waffle.io) que vamos a utilizar para la organización de las tareas y los issues. Por lo menos por el momento.
Avisen con un comentario cuando lo han instalado.

**Comment by torcaza12** [comment]
Listo

**Comment by mcupo** [comment]
Listo

**Comment by marianocat** [comment]
Listo!

**Comment by SergioRaimundo** [comment]
listo

**Comment by sobregoso** [comment]
listo
